### ISSUE TITLE
Does running tasks using gulp-ll help avoid "File table overflow" errors?

### ISSUE THREAD

**Issue by onlywei** [inikulin/gulp-ll#4]
Sorry I have another stupid question.

If I run linting and testing tasks in worker processes, should I expect that they don't use the same "file table" so I don't have to worry about too many files open at once? Or does the process not matter?

These tasks don't error when I run them in series, but when I try to run them at the same time I get the "File table overflow" error.

**Comment by inikulin** [comment]
> If I run linting and testing tasks in worker processes, should I expect that they don't use the same "file table" so I don't have to worry about too many files open at once? Or does the process not matter?

I can't provide any precise info here, since I've never ran into this problem. But, AFAIK "file table overflow"  is a system-wide error and it appears when cumulative number of open files across **all process** reaches the system limit. So, I guess it can be solved by adding new parallel processes.
